language: python
sudo: false
cache: pip
python:
 - "3.6"
 - "3.5"
 - "3.4"
 - "2.7"
install: pip install tox-travis
script: tox
addons:
  postgresql: 9.6
  apt:
    packages:
     - postgresql-9.6-postgis-2.3
