language: python
sudo: false
cache: pip

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

install:
    - pip install tox-travis python-coveralls

script:
    - tox

matrix:
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

after_success:
    coveralls
