language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y libgdal-dev libproj-dev libproj-dev spatialite-bin python-dev python3-dev

install:
    - pip install tox-travis python-coveralls
 
script:
    - tox

matrix:
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

after_success:
    coveralls
